import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Inter } from "next/font/google"
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";


import "react-loading-skeleton/dist/skeleton.css"

const inter = Inter({ subsets:['latin']})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <Providers>
      <body
        className={cn(`min-h-screen font-sans antialiased grainy`,inter.className)}
      >
        <Navbar />
        {children}
      </body>
      </Providers>
    </html>
  );
}
